### GET request to example server
GET http://localhost:8080/api/book/4

### GET request to example server
GET http://localhost:8080/api/book/4


###
### GET request to example server
GET http://localhost:8080/api/book/4


###
### GET request to example server
GET http://localhost:8080/api/book/4


###
### GET request to example server
GET http://localhost:8080/api/book/4


###
### GET request to example server
GET http://localhost:8080/api/book/4


###
### GET request to example server
GET http://localhost:8080/api/book/4


###
### GET request to example server
GET http://localhost:8080/api/book/4


###
### GET request to example server
GET http://localhost:8080/api/book/4


###
### GET request to example server
GET http://localhost:8080/api/book/order-report


###